SRCS += test/test_condition_variable/test_condition_variable.c
SRCS += test/test_condition_variable/test_condition_variable_1.c
SRCS += test/test_condition_variable/test_condition_variable_2.cpp
SRCS += test/test_condition_variable/test_condition_variable_3.cpp
