SRCS += test/test_mailbox_queue/test_mailbox_queue.c
SRCS += test/test_mailbox_queue/test_mailbox_queue_1.c
SRCS += test/test_mailbox_queue/test_mailbox_queue_2.cpp
SRCS += test/test_mailbox_queue/test_mailbox_queue_3.cpp
