PROJECT := test
IARCC   :=
DEFS    :=
INCS    := include
SRCS    := src/main.c
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/stateos/make/stm32f4discovery/makefile.iarcc
#----------------------------------------------------------#

include $(COMMON)/cmsis/makefile
include $(COMMON)/device/makefile
include $(COMMON)/startup/makefile
include $(COMMON)/stateos/makefile

#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
