PROJECT := test
CLANG   :=
DEFS    :=
INCS    := include
SRCS    := src/main.cpp
LIBS    :=
SCRIPT  :=
COMMON  := common

#----------------------------------------------------------#
include $(COMMON)/stateos/make/stm32f4discovery/makefile.clang
#----------------------------------------------------------#
include $(COMMON)/cmsis/makefile
include $(COMMON)/device/makefile
include $(COMMON)/startup/makefile
#----------------------------------------------------------#
include $(COMMON)/make/makefile
#----------------------------------------------------------#
