SRCS += test/test_message_queue/test_message_queue.c
SRCS += test/test_message_queue/test_message_queue_1.c
SRCS += test/test_message_queue/test_message_queue_2.cpp
SRCS += test/test_message_queue/test_message_queue_3.cpp
