SRCS += test/test_message_buffer/test_message_buffer.c
SRCS += test/test_message_buffer/test_message_buffer_1.c
SRCS += test/test_message_buffer/test_message_buffer_2.cpp
SRCS += test/test_message_buffer/test_message_buffer_3.cpp
