SRCS += test/test_memory_pool/test_memory_pool.c
SRCS += test/test_memory_pool/test_memory_pool_1.c
SRCS += test/test_memory_pool/test_memory_pool_2.cpp
SRCS += test/test_memory_pool/test_memory_pool_3.cpp
