SRCS += test/test_event_queue/test_event_queue.c
SRCS += test/test_event_queue/test_event_queue_1.c
SRCS += test/test_event_queue/test_event_queue_2.cpp
SRCS += test/test_event_queue/test_event_queue_3.cpp
